[game_params]
gravity = 0.016
soft_drop_factor = 40.0
das = 10.0
arr = 2.0
lock_delay = 30

[keys]
left = { keyboard = ["Left"], gamepad = ["DPadLeft"] }
right = { keyboard = ["Right"], gamepad = ["DPadRight"] }
next_rotation = { keyboard = ["X"], gamepad = ["East"] }
prev_rotation = { keyboard = ["Z"], gamepad = ["South"] }
pause = { keyboard = ["Return"], gamepad = ["Start"] }
soft_drop = { keyboard = ["Down"], gamepad = ["DPadDown"] }
hard_drop = { keyboard = ["Up"], gamepad = ["DPadUp"] }
hold = { keyboard = ["C"], gamepad = ["RightTrigger"] }
quit = { keyboard = ["Escape"], gamepad = ["RightTrigger2"] }
