[package]
name = "rust_tetris_ui_core"
version = "0.1.0"
authors = ["Davide Canton <davide.canton5@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
log = "0.4.11"
rust_tetris_core = { path = "../rust_tetris_core" }