[package]
name = "rust_tetris_standard_game"
version = "0.1.0"
authors = ["Davide Canton <davide.canton5@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.37.0"
pistoncore-glutin_window = "0.67.0"
piston2d-opengl_graphics = "0.74.0"
piston_window = "0.113.0"
rand = "0.7.3"
find_folder = "0.3.0"
rust_tetris_core = { path = "../rust_tetris_core" }
rust_tetris_ui_core = { path = "../rust_tetris_ui_core" }